# Generated by Django 4.1.13 on 2026-05-19 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('total_slots', models.IntegerField()),
                ('available_slots', models.IntegerField()),
                ('cluster_label', models.CharField(blank=True, choices=[('high_demand', 'High-Demand'), ('moderate', 'Moderate-Use'), ('low_traffic', 'Low-Traffic')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('maintenance', 'Maintenance')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=50)),
                ('slot_type', models.CharField(choices=[('regular', 'Regular'), ('disabled', 'Disabled')], default='regular', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=20)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkinglot')),
            ],
            options={
                'unique_together': {('lot', 'slot_number')},
            },
        ),
        migrations.CreateModel(
            name='OccupancyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('occupancy_percentage', models.FloatField()),
                ('day_of_week', models.IntegerField()),
                ('hour_of_day', models.IntegerField()),
                ('is_weekend', models.BooleanField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='parking.parkinglot')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.parkingslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='occupancyrecord',
            index=models.Index(fields=['lot', 'recorded_at'], name='parking_occ_lot_id_c26414_idx'),
        ),
    ]
