# Generated by Django 4.1.13 on 2026-05-22 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        # MongoDB is schemaless — no ALTER TABLE needed.
        # SeparateDatabaseAndState updates Django's model state without
        # running any SQL against the database.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='parkinglot',
                    name='latitude',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='parkinglot',
                    name='longitude',
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='occupancyrecord',
                    name='recorded_at',
                    field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
            database_operations=[],
        ),
    ]
